if SERVER then
	util.AddNetworkString("NetEffectData")
	util.AddNetworkString("NetDecalData")
	function netEffect( name, data )
		local angle = data:GetAngles()
		local attachment = data:GetAttachment()
		local color = data:GetColor()
		local ent = data:GetEntity()
		local dmg = data:GetDamageType()
		local entIndex = data:GetEntIndex()
		local flag = data:GetFlags()
		local hitbox = data:GetHitBox()
		local mag = data:GetMagnitude()
		local mat = data:GetMaterialIndex()
		local normal = data:GetNormal()
		local origin = data:GetOrigin()
		local radius = data:GetRadius()
		local scale = data:GetScale()
		local start = data:GetStart()
		local surf = data:GetSurfaceProp()
		
		
		net.Start("NetEffectData")
			net.WriteString( name )
			net.WriteAngle( angle )
			net.WriteString( attachment )
			net.WriteString( color )
			net.WriteEntity( ent )
			net.WriteString( dmg )
			net.WriteString( entIndex )
			net.WriteString( flag )
			net.WriteString( hitbox )
			net.WriteString( mag )
			net.WriteString( mat )
			net.WriteVector( normal )
			net.WriteVector( origin )
			net.WriteString( radius )
			net.WriteString( scale )
			net.WriteVector( start )
			net.WriteString( surf )
		net.Broadcast()
		
	end
	function netDecal( name, pos1, pos2 )
		net.Start("NetDecalData")
			net.WriteString( name )
			net.WriteVector( pos1 )
			net.WriteVector( pos2 )
		net.Broadcast()
	end
else
	net.Receive("NetEffectData", function( len )
		local name = net.ReadString()
		local angle = net.ReadAngle()
		local attachment = tonumber(net.ReadString())
		local color = tonumber(net.ReadString())
		local ent = net.ReadEntity()
		local dmg = tonumber(net.ReadString())
		local entIndex = tonumber(net.ReadString()) or 0
		local flag = tonumber(net.ReadString())
		local hitbox = tonumber(net.ReadString())
		local mag = tonumber(net.ReadString())
		local mat = tonumber(net.ReadString())
		local normal = net.ReadVector()
		local origin = net.ReadVector()
		local radius = tonumber(net.ReadString())
		local scale = tonumber(net.ReadString())
		local start = net.ReadVector()
		local surf = tonumber(net.ReadString()) or 0

		local neteffect = EffectData()
			neteffect:SetAngles( angle )
			neteffect:SetAttachment( attachment )
			neteffect:SetColor( color )
			neteffect:SetEntity( ent )
			neteffect:SetDamageType( dmg )
			//neteffect:SetEntIndex( entIndex )
			neteffect:SetFlags( flag )
			neteffect:SetHitBox( hitbox )
			neteffect:SetMagnitude( mag )
			neteffect:SetMaterialIndex( mat )
			neteffect:SetNormal( normal )
			neteffect:SetOrigin( origin )
			neteffect:SetRadius( radius )
			neteffect:SetScale( scale )
			neteffect:SetStart( start )
			neteffect:SetSurfaceProp( surf )
		util.Effect(name, neteffect)
	end)
	net.Receive("NetDecalData", function( len )
		local name = net.ReadString()
		local pos1 = net.ReadVector()
		local pos2 = net.ReadVector()
		util.Decal( name, pos1, pos2)
	end)
end